stages:
  - build
  - test

default:
  image: gradle:jdk17

before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - echo -e "\e[1;34mBuilding the application\e[0m"
    - ./gradlew clean assemble

test:
  stage: test
  script:
    - echo -e "\e[1;34mTesting the application\e[0m"
    - ./gradlew check