version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: art_commissions_db
    environment:
      - POSTGRES_USER=tjv
      - POSTGRES_PASSWORD=tjv
      - POSTGRES_DB=tjv_db
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data
  server:
    image: cz.cvut.fit.tjv.art_commissions.app.snapi
    depends_on:
      - postgres
    ports:
      - '8080:8080'

  client:
    image: cz.cvut.fit.tjv.art_commissions.app.sclient
    depends_on:
      - server
    ports:
      - '8081:8081'
    environment:
      server.url: http://server:8080