CREATE TABLE artist
(
    id_artist      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    price_per_hour INTEGER                                 NOT NULL,
    art_type       INTEGER,
    id_coworker    BIGINT,
    CONSTRAINT pk_artist PRIMARY KEY (id_artist)
);

ALTER TABLE artist
    ADD CONSTRAINT FK_ARTIST_ON_ID_COWORKER FOREIGN KEY (id_coworker) REFERENCES artist (id_artist);

CREATE TABLE customer
(
    id_customer BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id_customer)
);

CREATE TABLE commission
(
    id_commission      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    art_type           INTEGER,
    description        VARCHAR(255),
    estimated_hours    INTEGER                                 NOT NULL,
    issuing_date       date,
    estimated_end_date date,
    price              INTEGER                                 NOT NULL,
    id_customer        BIGINT,
    CONSTRAINT pk_commission PRIMARY KEY (id_commission)
);

CREATE TABLE commission_artist
(
    id_artist     BIGINT NOT NULL,
    id_commission BIGINT NOT NULL,
    CONSTRAINT pk_commission_artist PRIMARY KEY (id_artist, id_commission)
);

ALTER TABLE commission
    ADD CONSTRAINT FK_COMMISSION_ON_ID_CUSTOMER FOREIGN KEY (id_customer) REFERENCES customer (id_customer);

ALTER TABLE commission_artist
    ADD CONSTRAINT fk_comart_on_artist FOREIGN KEY (id_artist) REFERENCES artist (id_artist);

ALTER TABLE commission_artist
    ADD CONSTRAINT fk_comart_on_commission FOREIGN KEY (id_commission) REFERENCES commission (id_commission);